SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS assignment_class;
DROP TABLE IF EXISTS assignment_files;
DROP TABLE IF EXISTS assignments;
DROP TABLE IF EXISTS backpack;
DROP TABLE IF EXISTS class_subjects_faculty;
DROP TABLE IF EXISTS class_subjects;
DROP TABLE IF EXISTS class;
DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS faculty;
DROP TABLE IF EXISTS faculties;
DROP TABLE IF EXISTS lessons;
DROP TABLE IF EXISTS student_class;
DROP TABLE IF EXISTS student_grades;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS subjects;
DROP TABLE IF EXISTS system_info;
DROP TABLE IF EXISTS upload_files;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS lesson_class;
DROP TABLE IF EXISTS academic_year;
DROP TABLE IF EXISTS faculty; -- in case duplicated

CREATE TABLE academic_year (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sy VARCHAR(150) NOT NULL,
  status TINYINT(5) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE subjects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  subject_code VARCHAR(50) NOT NULL,
  subject_name VARCHAR(255) NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE faculties (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE faculty (
  id INT AUTO_INCREMENT PRIMARY KEY,
  faculty_id VARCHAR(50) NOT NULL,
  department_id INT NOT NULL,
  firstname VARCHAR(150) NOT NULL,
  middlename VARCHAR(150) NOT NULL,
  lastname VARCHAR(150) NOT NULL,
  email VARCHAR(250) NOT NULL,
  contact VARCHAR(150) NOT NULL,
  gender VARCHAR(20) NOT NULL,
  address TEXT,
  password TEXT,
  dob INT NOT NULL,
  avatar TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE department (
  id INT AUTO_INCREMENT PRIMARY KEY,
  department VARCHAR(255) NOT NULL,
  description TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE course (
  id INT AUTO_INCREMENT PRIMARY KEY,
  course VARCHAR(255) NOT NULL,
  description TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE class (
  id INT AUTO_INCREMENT PRIMARY KEY,
  department_id INT NOT NULL,
  course_id INT NOT NULL,
  level VARCHAR(50),
  section VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id VARCHAR(50) NOT NULL,
  firstname VARCHAR(150) NOT NULL,
  middlename VARCHAR(150) NOT NULL,
  lastname VARCHAR(150) NOT NULL,
  email VARCHAR(250) NOT NULL,
  contact VARCHAR(150) NOT NULL,
  gender VARCHAR(20) NOT NULL,
  address TEXT,
  password TEXT,
  dob INT NOT NULL,
  avatar TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE lessons (
  id INT AUTO_INCREMENT PRIMARY KEY,
  academic_year_id INT NOT NULL,
  subject_id INT NOT NULL,
  faculty_id VARCHAR(50) NOT NULL,
  title VARCHAR(250) NOT NULL,
  description TEXT,
  ppt_path TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE assignments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  subject_id INT NOT NULL,
  description TEXT NOT NULL,
  academic_year_id INT NOT NULL,
  faculty_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (subject_id) REFERENCES subjects(id),
  FOREIGN KEY (academic_year_id) REFERENCES academic_year(id),
  FOREIGN KEY (faculty_id) REFERENCES faculties(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE assignment_files (
  id INT AUTO_INCREMENT PRIMARY KEY,
  assignment_id INT NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (assignment_id) REFERENCES assignments(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE assignment_class (
  id INT AUTO_INCREMENT PRIMARY KEY,
  assignment_id INT NOT NULL,
  class_id INT NOT NULL,
  FOREIGN KEY (assignment_id) REFERENCES assignments(id) ON DELETE CASCADE,
  FOREIGN KEY (class_id) REFERENCES class(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE class_subjects (
  academic_year_id INT NOT NULL,
  class_id INT NOT NULL,
  subject_id INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE class_subjects_faculty (
  id INT AUTO_INCREMENT PRIMARY KEY,
  class_id INT NOT NULL,
  subject_id INT NOT NULL,
  faculty_id INT NOT NULL,
  academic_year_id INT NOT NULL,
  FOREIGN KEY (class_id) REFERENCES class(id) ON DELETE CASCADE,
  FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE,
  FOREIGN KEY (faculty_id) REFERENCES faculties(id) ON DELETE CASCADE,
  FOREIGN KEY (academic_year_id) REFERENCES academic_year(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE backpack (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  upload_file_id INT NOT NULL,
  lesson_id INT NOT NULL,
  pinned TINYINT DEFAULT 0,
  date_created DATETIME DEFAULT CURRENT_TIMESTAMP,
  date_updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE student_class (
  id INT AUTO_INCREMENT PRIMARY KEY,
  academic_year_id INT NOT NULL,
  student_id INT NOT NULL,
  class_id INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE student_grades (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT NOT NULL,
  lesson_id INT NOT NULL,
  subject_id INT NOT NULL,
  assignment_score INT DEFAULT 0,
  exam_score INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_index (student_id, lesson_id, subject_id),
  FOREIGN KEY (student_id) REFERENCES students(id),
  FOREIGN KEY (lesson_id) REFERENCES lessons(id),
  FOREIGN KEY (subject_id) REFERENCES subjects(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE system_info (
  id INT AUTO_INCREMENT PRIMARY KEY,
  meta_field TEXT NOT NULL,
  meta_value TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE upload_files (
  id INT AUTO_INCREMENT PRIMARY KEY,
  filename TEXT NOT NULL,
  file_path TEXT NOT NULL,
  faculty_id INT NOT NULL,
  date_created DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(250) NOT NULL,
  lastname VARCHAR(250) NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  avatar TEXT,
  last_login DATETIME,
  date_added DATETIME DEFAULT CURRENT_TIMESTAMP,
  date_updated DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE lesson_class (
  lesson_id INT NOT NULL,
  class_id INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Add indexes and AUTO_INCREMENT modifications if needed...

SET FOREIGN_KEY_CHECKS=1;

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
